# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEvWc8SCce4Y2o42gbxxLqL6JeIoY5U8
"""

!pip install streamlit

!pip install pandas

import streamlit as st
import pandas as pd

# Load data
@st.cache_data
def load_data():
    return pd.read_csv("Updated_Dataset_With_Recovery_Status.csv")

df = load_data()

st.title("Patient Dataset Dashboard")

# Filter section
st.sidebar.header("Filter Records")
name_filter = st.sidebar.text_input("Search by Patient Name")
disease_filter = st.sidebar.selectbox("Select Disease", ["All"] + sorted(df['Primary_Diagnosis'].dropna().unique().tolist()))

# Apply filters
filtered_df = df.copy()
if name_filter:
    filtered_df = filtered_df[filtered_df['Name'].str.contains(name_filter, case=False, na=False)]

if disease_filter != "All":
    filtered_df = filtered_df[filtered_df['Primary_Diagnosis'] == disease_filter]

# Display filtered data
st.subheader("Filtered Patient Records")
st.dataframe(filtered_df)

# Show summary
st.subheader("Summary Statistics")
st.write(filtered_df.describe(include='all'))

# Download option
st.download_button("Download Filtered Data", filtered_df.to_csv(index=False), file_name="filtered_data.csv")